
- name: Get miniconda for Mac OSX
  get_url:
    url: https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh
    dest: /tmp/miniconda.sh
  when: ansible_os_family == "Darwin"

# 64-bit linux installer
- name: Get miniconda for Linux
  get_url:
    url: https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
    dest: /tmp/miniconda.sh
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

- name: Run the miniconda installer
  command: bash /tmp/miniconda.sh -b -p ~/miniconda
  args:
    creates: "{{dotfiles_user_home}}/miniconda"
